services:
  traefik:
    networks:
      default:
        aliases:
          - ${DOMAIN}
          - adguard.${DOMAIN}
          - cronmaster.${DOMAIN}
          - downly.${DOMAIN}
          - dynamodb-dashboard.${DOMAIN}
          - dynamodb.${DOMAIN}
          - frigate.${DOMAIN}
          - immich.${DOMAIN}
          - jellyfin.${DOMAIN}
          - karakeep.${DOMAIN}
          - minio.${DOMAIN}
          - n8n.${DOMAIN}
          - nextcloud.${DOMAIN}
          - passbolt.${DOMAIN}
          - pgweb.${DOMAIN}
          - portainer.${DOMAIN}
          - postgres.${DOMAIN}
          - redis-insight.${DOMAIN}
          - redis.${DOMAIN}
          - syncthing.${DOMAIN}
          - traefik.${DOMAIN}
